### ISSUE TITLE
 Didn't find class "android.support.design.widget.CoordinatorLayout"

### ISSUE THREAD

**Issue by jackmatt2** [ProteanSoftware/capacitor-start-navigation#1]
Not too familiar with android these days but it looks like there is an issue with **androidx**.  The latest ionic cli generates using **androidx** dependencies so this plugin does not work.

https://stackoverflow.com/questions/32838594/error-inflating-class-android-support-design-widget-coordinatorlayout-and-classn/52490825

Won't load and errors with

`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.CoordinatorLayout"`

**Comment by AshleyMedway** [comment]
Yeah I haven’t updated it for androidx yet, will do it soon :)

Does it not work with jetifier? We are using this in production with jetifier. 

https://capacitorjs.com/docs/android/updating#from-1-5-1-to-2-0-0

**Comment by AshleyMedway** [comment]
I've just published 3.0.0 with the androidx changes give it a go and let me know if it works :)

https://www.npmjs.com/package/@proteansoftware/capacitor-start-navigation/v/3.0.0

**Comment by jackmatt2** [comment]
Yes - works great now thanks.
