### ISSUE TITLE
Official Capacitor v5 Support

### ISSUE THREAD

**Issue by cwoebker** [ProteanSoftware/capacitor-start-navigation#14]
Hi, I saw that there is a beta version for v5 in NPM: https://www.npmjs.com/package/@proteansoftware/capacitor-start-navigation/v/5.0.0-beta1

I didn't find any announcement or issue in this repository so far on Capacitor v5 support.
Are you planning to release full support soon or are there any outstanding issues that still need to be fixed?

Thanks for the work on this!

**Comment by AshleyMedway** [comment]
Sorry v5 upgrades just went on the back burner, published now :)
