### ISSUE TITLE
Not working with Capacitor 4

### ISSUE THREAD

**Issue by pdrhlik** [ProteanSoftware/capacitor-start-navigation#5]
Hi,

I tried installing the plugin inside a Capacitor 4 app on Android. Unfortunately, the app didn't even start. Maybe it needs to be updated to be compatible?

Thanks,
Patrik

**Comment by pdrhlik** [comment]
So it apparently works with Capacitor 4. The only thing that changed is that you don't have to register the plugin in `MainActivity.java` and it works out of the box.

**Comment by AshleyMedway** [comment]
Yeah this was actually a change in capacitor 3, I will update the documentation :)
