### ISSUE TITLE
Use address instead of lat/long

### ISSUE THREAD

**Issue by tysonlist** [ProteanSoftware/capacitor-start-navigation#7]
Based on a quick review, it seems possible to support address instead of lat/long for both android & ios.

Is this functionality something you'd be open to adding to this repository/accept a pull request for?

Sources:
https://developer.apple.com/documentation/corelocation/clgeocoder
https://developers.google.com/maps/documentation/urls/android-intents

**Comment by AshleyMedway** [comment]
Hey, our use case was only for coordinates but more than happy to add this functionality. If you want to do a PR feel free otherwise I will try and get round to it this week :)

**Comment by AshleyMedway** [comment]
@tysonlist are you able to test this functionality? 

```
npm i @proteansoftware/capacitor-start-navigation@4.1.0-alpha
```

## Usage

```ts
import { StartNavigation } from "@proteansoftware/capacitor-start-navigation";

//
// launches native maps with directions to Warwick, UK
StartNavigation.launchMapsApp({
  address: {
    street: "Market Place",
    city: "Warwick",
    postalCode: "CV34 4SA",
    Country: "United Kingdom"
  },
  name: "Example location"
});

**Comment by tysonlist** [comment]
I will do some testing next week and let you know!

**Comment by AshleyMedway** [comment]
No rush, have a good Christmas break :)

**Comment by AshleyMedway** [comment]
@tysonlist were you able to test this functionality?

**Comment by tysonlist** [comment]
Sorry for the delay. Here's the results of my tests.
- IOS: works as expected
- Web: returns error
- Android: did not test (I will try again later this week)

**Comment by tysonlist** [comment]
@AshleyMedway Android works as expected. Will web be supported or not?

**Comment by AshleyMedway** [comment]
@tysonlist `4.2.0-alpha` should have web support, it also has the travel mode feature merged in.

```
npm i @proteansoftware/capacitor-start-navigation@4.2.0-alpha

**Comment by tysonlist** [comment]
@AshleyMedway 
Latest Version Testing: `4.2.0-alpha`

- IOS: Works as expected
- WEB: Works as expected
- ANDROID: Error - destination shows zeroed lat/lng before querystring:
`0.0,0.0?q=address sample redacted` 
I double checked once again and my previous android tests apparently also failed, so I apologize for incorrectly reported successful result.

**Comment by AshleyMedway** [comment]
@tysonlist thanks for the contribution, published as @proteansoftware/capacitor-start-navigation@4.2.0-alpha2

```
npm i @proteansoftware/capacitor-start-navigation@4.2.0-alpha2

**Comment by tysonlist** [comment]
Verified functionality using `4.2.0-alpha2`. Please let me know once it's published!

**Comment by AshleyMedway** [comment]
Published, thanks for the help :)

```
@proteansoftware/capacitor-start-navigation@4.2.0
